# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
                ('allowsTransactions', models.BooleanField(verbose_name=bool)),
                ('balance', models.FloatField(verbose_name=float)),
                ('state', models.FloatField(verbose_name=float)),
            ],
        ),
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatId', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
                ('datetime', models.DateField()),
                ('amount', models.FloatField(verbose_name=float)),
                ('state', models.BooleanField(verbose_name=bool)),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AccountingAccounts')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=2)),
                ('state', models.BooleanField(verbose_name=bool)),
            ],
        ),
        migrations.CreateModel(
            name='AuxiliarOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lavelId', models.CharField(max_length=5)),
                ('description', models.CharField(max_length=20)),
                ('lastExchangeRate', models.FloatField(verbose_name=float)),
                ('state', models.BooleanField(verbose_name=bool)),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Majorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountId', models.CharField(max_length=30)),
                ('datetime', models.DateField()),
                ('balance', models.FloatField(verbose_name=float)),
                ('state', models.BooleanField(verbose_name=bool)),
                ('majorAccountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AccountingAccounts')),
            ],
        ),
        migrations.CreateModel(
            name='MovementTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name=int)),
                ('month', models.IntegerField(verbose_name=int)),
                ('majorizationProcessed', models.BooleanField(verbose_name=bool)),
                ('companyRNC', models.IntegerField(verbose_name=int)),
                ('taxClosingMonth', models.IntegerField(verbose_name=int)),
            ],
        ),
        migrations.AddField(
            model_name='majorization',
            name='movementTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MovementTypes'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='auxiliarOriginId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AuxiliarOrigin'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='movementTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MovementTypes'),
        ),
        migrations.AddField(
            model_name='accountingaccounts',
            name='accountTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AccountTypes'),
        ),
        migrations.AddField(
            model_name='accountingaccounts',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Levels'),
        ),
        migrations.AddField(
            model_name='accountingaccounts',
            name='majorAccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AccountingAccounts'),
        ),
    ]
