# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingAccounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('description', models.CharField(max_length=30, verbose_name='Descripción')),
                ('allowsTransactions', models.BooleanField(verbose_name='Permitir Transacciones?')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], verbose_name='Nivel')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Balance')),
                ('state', models.BooleanField(verbose_name='Activo?')),
            ],
        ),
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, verbose_name='Descripción')),
                ('auxiliarOrigin', models.PositiveSmallIntegerField(choices=[(1, '1'), (6, '6')], verbose_name='Auxiliar')),
                ('datetime', models.DateField(blank=True, verbose_name='Fecha')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Monto')),
                ('state', models.BooleanField(verbose_name='Activo?')),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AccountingAccounts')),
            ],
        ),
        migrations.CreateModel(
            name='AccountTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, verbose_name='Descripción')),
                ('origin', models.CharField(choices=[('DB', 'Debito'), ('CR', 'Credito')], max_length=3, verbose_name='Origen')),
                ('state', models.BooleanField(verbose_name='Activo?')),
            ],
        ),
        migrations.CreateModel(
            name='AuxiliarOrigin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyTypes',
            fields=[
                ('iso', models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='ISO')),
                ('code', models.CharField(default='', max_length=5, verbose_name='Código')),
                ('symbol', models.CharField(default='', max_length=5, verbose_name='Símbolo')),
                ('description', models.CharField(max_length=20, verbose_name='Descripción')),
                ('lastExchangeRate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Última Tasa Cambiaria')),
                ('state', models.BooleanField(verbose_name='Activo?')),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Majorization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(verbose_name='Fecha')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Monto')),
                ('state', models.BooleanField(verbose_name='Activo?')),
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Majorization_accountId', to='app.AccountingAccounts')),
                ('majorAccountId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Majorization_majorAccountId', to='app.AccountingAccounts')),
            ],
        ),
        migrations.CreateModel(
            name='MovementTypes',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('month', models.IntegerField(verbose_name='Mes')),
                ('majorizationProcessed', models.BooleanField(verbose_name='Mayorización procesada')),
                ('companyRNC', models.IntegerField(verbose_name='Empresa RNC')),
                ('taxClosingMonth', models.IntegerField(verbose_name='Mes Cierre Fiscal')),
            ],
        ),
        migrations.AddField(
            model_name='majorization',
            name='movementTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MovementTypes'),
        ),
        migrations.AddField(
            model_name='accountingentry',
            name='movementTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.MovementTypes'),
        ),
        migrations.AddField(
            model_name='accountingaccounts',
            name='accountTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AccountTypes', verbose_name='Tipo de uenta'),
        ),
        migrations.AddField(
            model_name='accountingaccounts',
            name='majorAccount',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.AccountingAccounts', verbose_name='Cuenta Major'),
        ),
    ]
