# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingentry',
            name='auxiliarOrigin',
            field=models.IntegerField(default=1, verbose_name='Auxiliar'),
        ),
    ]
