# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingaccounts',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='accountingaccounts',
            name='majorAccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.AccountingAccounts'),
        ),
    ]
